### ISSUE TITLE
create about page component

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#73]
TBA

**Comment by brett-halperin** [comment]
Mockup 
![image](https://user-images.githubusercontent.com/35778453/125211535-e235a580-e25b-11eb-9f2c-01bb9a2cbc3b.png)

**Comment by boraerden** [comment]
same as the resources page 

done with https://github.com/antievictionmappingproject/covid-19-map-react/commit/1d769b1e025eb1ad8b9cc581961f426480efa724

i'm not sure if you were thinking a model @brett-halperin but it was really quick to implement that way since modal are already styled. feel free to reopen if this is not what you had in mind!
