### ISSUE TITLE
search bar doesn't work on protections map

### ISSUE THREAD

**Issue by lisjak** [antievictionmappingproject/covid-19-map-react#87]
- ✅ search bar populates with city (etc) suggestions when typing a city name 
- ❌ clicking on a suggested item in the search bar does not result in info window displaying 
- ❌ hitting enter doesn't do anything either 
- ❌  tested in Chrome and Firefox on Mac OS

current state:

![Screen Recording 2021-08-25 at 5 38 12 PM](https://user-images.githubusercontent.com/41743572/130868628-ac6a9013-ac45-4b87-b797-7245437f1d5c.gif)

**Comment by brett-halperin** [comment]
@jimboweb @benjaminben @boraerden are one of you able to give us a hand with this? thanks so much!

**Comment by lisjak** [comment]
Looks like the search function is working on the [old repo](https://github.com/antievictionmappingproject/covid-19-map), so this may be the result of the refactor for combining the two maps.

**Comment by boraerden** [comment]
hey all, just fixed this issue in a new branch dd5c02f51908a7a1fdaa546703626e688e5501c1 (and the following commit deletes a console log i left lingering eb3b3a045b6297dad50bdba3c9aea5b30bb6514e). 

I had to change the node-sass dependency because it looks like it doesn't support my current operating system, so if you want to avoid bringing in that change to the dev and main branches, i'm attaching a screenshot of the one-liner fix

![Screen Shot 2022-01-16 at 11 36 40 AM](https://user-images.githubusercontent.com/7088004/149669013-70d3d4e6-9c48-43bf-9289-e7dde1fc0ad2.png)

**Comment by brett-halperin** [comment]
Thanks for taking this on @boraerden and @lisjak - looks like still not working for me on mac chrome?

**Comment by boraerden** [comment]
i didn't pull it to the deployed branch yet, so the fix hasn't be integrated yet. i'm hesitant to deploy given the node-sass dependency i mentioned, so if @lisjak could do it, i think it would be best. but if not, tonight i can deploy on a test branch before changing the publicly deployed version.

**Comment by lisjak** [comment]
@boraerden @brett-halperin I'll get to work on merging the fix without the dependency now. Thanks so much for identifying this solution, Bora! 🎉

**Comment by lisjak** [comment]
merge in #122 deployed and live 🥳
